### ISSUE TITLE
annotated data format

### ISSUE THREAD

**Issue by nahidalam** [Chris-hughes10/Yolov7-training#16]
I was looking into your [blog post ](https://towardsdatascience.com/yolov7-a-deep-dive-into-the-current-state-of-the-art-for-object-detection-ce3ffedeeaeb#0c9c)and the codebase here. Your annotation file is a `.csv`. Which format is this annotated? COCO format or yolo format?

**Comment by Chris-hughes10** [comment]
Hi, the csv file has annotations in xyxy format. The way that we have approached this in the blog post is that your dataset adaptor should return xyxy boxes, so that it works cleanly with all of the augmentations, and then it will be converted to yolo format by the `Yolov7Dataset`.

Hope this helps!
